# Generated by Django 3.2.7 on 2021-11-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_post_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
