# Generated by Django 3.2.7 on 2021-12-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
